### ISSUE TITLE
Not work with Xcode 6.1.1 (6A2008a)

### ISSUE THREAD

**Issue by zotix** [githotto/osxgmp#1]
I try to run example code and found it.

dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Users/Billy/Library/Developer/Xcode/DerivedData/OSXGMP-domiqkbozvoftldratvtsnfdukik/Build/Products/Debug/OSXGMP
  Reason: image not found
(lldb)

**Comment by githotto** [comment]
Hello Zotix,
The 'Library  not loaded' can sometimes occur if you haven't installed
Xcode-CommandLine tools. Using your AppleID in AppleDevMemberCenter you can
download them separately or follow the recipe in
http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/
For the "Reason: image not found" I've no explanation yet, and I'll try to
get my hands on a clean MacOSX machine in which I install a fresh Xcode
with the OSXGMP to see what really happens. I'll let you know if I've found
a solution for this.
Sorry in advance for the inconvenience caused by this issue.
Thanks anyway for trying to use the OSXGMP, cheers,
Otto van Verseveld

2015-01-18 10:08 GMT+01:00 zotix notifications@github.com:

**Comment by zotix** [comment]
I found the solution just copy "libgmp.10.dylib" in GMP to "/usr/local/lib/libgmp.10.dylib"
Thanks for your support :+1:
